version: '3.1'

services:

  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:007934561cgtfru@postgres:5432/bank
      PORT: 3000
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 007934561cgtfru
      POSTGRES_USER: postgres
      POSTGRES_DB: bank
    ports:
    - "5432:5432"
