version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:007934561cgtfru@postgres:5432/bank
      REDIS_PORT: 6379
      REDIS_HOST: redis
      REDIS_USERNAME: default
      MONGO_URL: mongodb://mongodb:27017
    networks:
      - db_network
    depends_on:
      - postgres
      - mongodb
      - redis
    entrypoint: dockerize -wait tcp://postgres:5432 -wait tcp://mongodb:27017 -wait tcp://redis:6379 -timeout 20s docker-entrypoint.sh
    command: sh -c "npx prisma db push && npm start"

  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 007934561cgtfru
      POSTGRES_USER: postgres
      POSTGRES_DB: bank
    networks:
      - db_network
    ports:
      - '5432:5432'

  mongodb:
    image: mongo
    container_name: mongo-db
    restart: always
    networks:
      - db_network
    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: redis-db
    restart: always
    networks:
      - db_network
    ports:
      - '6379:6379'

networks:
  db_network:
    driver: bridge

volumes:
  data: